added root_dir to set where the runner looks for steps to import
in djnago 1.9 this causes the models.py file to attempt import causing an error like:

RuntimeError: Model class models.<Your model> doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.